
package com.zsy.net.webservice.test;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ECGAdaptor", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/Test/File/ECGAdaptor.wsdl")
public class ECGAdaptor extends Service {

    private final static URL ECGADAPTOR_WSDL_LOCATION;
    private final static WebServiceException ECGADAPTOR_EXCEPTION;
    private final static QName ECGADAPTOR_QNAME = new QName("http://tempuri.org/", "ECGAdaptor");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/ECGAdaptor/ECGAdaptor.asmx");//file:/D:/Test/File/ECGAdaptor.wsdl
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECGADAPTOR_WSDL_LOCATION = url;
        ECGADAPTOR_EXCEPTION = e;
    }

    public ECGAdaptor() {
        super(__getWsdlLocation(), ECGADAPTOR_QNAME);
    }

    public ECGAdaptor(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECGADAPTOR_QNAME, features);
    }

    public ECGAdaptor(URL wsdlLocation) {
        super(wsdlLocation, ECGADAPTOR_QNAME);
    }

    public ECGAdaptor(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECGADAPTOR_QNAME, features);
    }

    public ECGAdaptor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ECGAdaptor(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ECGAdaptorSoap
     */
    @WebEndpoint(name = "ECGAdaptorSoap")
    public ECGAdaptorSoap getECGAdaptorSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorSoap"), ECGAdaptorSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ECGAdaptorSoap
     */
    @WebEndpoint(name = "ECGAdaptorSoap")
    public ECGAdaptorSoap getECGAdaptorSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorSoap"), ECGAdaptorSoap.class, features);
    }

    /**
     * @return returns ECGAdaptorSoap
     */
    @WebEndpoint(name = "ECGAdaptorSoap12")
    public ECGAdaptorSoap getECGAdaptorSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorSoap12"), ECGAdaptorSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ECGAdaptorSoap
     */
    @WebEndpoint(name = "ECGAdaptorSoap12")
    public ECGAdaptorSoap getECGAdaptorSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorSoap12"), ECGAdaptorSoap.class, features);
    }

    /**
     * @return returns ECGAdaptorHttpGet
     */
    @WebEndpoint(name = "ECGAdaptorHttpGet")
    public ECGAdaptorHttpGet getECGAdaptorHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorHttpGet"), ECGAdaptorHttpGet.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ECGAdaptorHttpGet
     */
    @WebEndpoint(name = "ECGAdaptorHttpGet")
    public ECGAdaptorHttpGet getECGAdaptorHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorHttpGet"), ECGAdaptorHttpGet.class, features);
    }

    /**
     * @return returns ECGAdaptorHttpPost
     */
    @WebEndpoint(name = "ECGAdaptorHttpPost")
    public ECGAdaptorHttpPost getECGAdaptorHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorHttpPost"), ECGAdaptorHttpPost.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ECGAdaptorHttpPost
     */
    @WebEndpoint(name = "ECGAdaptorHttpPost")
    public ECGAdaptorHttpPost getECGAdaptorHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ECGAdaptorHttpPost"), ECGAdaptorHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECGADAPTOR_EXCEPTION != null) {
            throw ECGADAPTOR_EXCEPTION;
        }
        return ECGADAPTOR_WSDL_LOCATION;
    }

}
