/*
javah -classpath . -jni com.zsy.jni.JNIDemo
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsy_jni_JNIDemo */

#ifndef _Included_com_zsy_jni_JNIDemo
#define _Included_com_zsy_jni_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsy_jni_JNIDemo
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsy_jni_JNIDemo_testHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
