
package com.zsy.net.webservice.test4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param param
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = ".............")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMobileCodeInfo", targetNamespace = "http://example/", className = "com.zsy.webservice.test4.GetMobileCodeInfo")
    @ResponseWrapper(localName = "getMobileCodeInfoResponse", targetNamespace = "http://example/", className = "com.zsy.webservice.test4.GetMobileCodeInfoResponse")
    @Action(input = ".............", output = "http://example/HelloWorld/getMobileCodeInfoResponse")
    public String getMobileCodeInfo(
        @WebParam(name = "param", targetNamespace = "")
        String param);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AAA")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AAA", targetNamespace = "http://example/", className = "com.zsy.webservice.test4.AAA")
    @ResponseWrapper(localName = "AAAResponse", targetNamespace = "http://example/", className = "com.zsy.webservice.test4.AAAResponse")
    @Action(input = "http://example/HelloWorld/AAARequest", output = "http://example/HelloWorld/AAAResponse")
    public String aaa(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
